### Numpy数组

In [5]:
import numpy as np

#### 从头创建数组

In [8]:
# 嵌套列表构成多维数组
n1 = np.array([[range(i,i+3)] for i in [2,4,6]])
n1

array([[[2, 3, 4]],

       [[4, 5, 6]],

       [[6, 7, 8]]])

In [11]:
# 创建一个长度为10的全零数组
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
# 创建一个3x5的浮点型全1数组
np.ones((3,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#创建一个3x5的浮点型数组，数组的值都是Π
np.full((3,5),np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265, 3.14159265]])

In [13]:
#创建一个步长为2的线性序列数组
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [14]:
# 创建一个5个元素的数组，均分于（0，1）之间
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
# 创建一个3x3的，再0~1之间均匀分布的随机数组成数组
np.random.random((3,3))

array([[0.22634498, 0.9360439 , 0.54328119],
       [0.75428314, 0.6724242 , 0.62053929],
       [0.98124888, 0.79645893, 0.49225913]])

In [16]:
# 创建一个3x3，均值为0，方差为1的正态分布随机数组
np.random.normal(0,1,(3,3))

array([[-1.72136147,  0.3074046 , -0.61848752],
       [ 1.23119809,  1.2088077 , -0.18726648],
       [ 1.1642788 , -0.51130658,  0.65581209]])

In [17]:
# 创建一个3*3，【0，10）区间的随机整数数组
np.random.randint(0,10,(3,3))

array([[1, 5, 3],
       [2, 6, 1],
       [4, 6, 0]])

In [18]:
# 创建一个3*3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# 创建一个由3个整型数组组成的未初始化的数组
np.empty(3)

array([1., 1., 1.])

#### Numpy数组基础

In [40]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size = (3,4))
x3 = np.random.randint(10, size = (3,4,5))
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


#### Numpy数组的变形

In [42]:
# 通过reshape（）函数实现数组的变形
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
#将一维数组转变为二维的行或列的矩阵
x = np.array([1,2,3])
print("行向量：",x.reshape((1,3)))
print("列向量：",x.reshape((3,1)))

行向量： [[1 2 3]]
列向量： [[1]
 [2]
 [3]]


In [57]:
# 通过newaxis也可以实现同样的效果
print('行向量:',x[np.newaxis,:])
print('列向量:',x[:,np.newaxis])

行向量: [[1 2 3]]
列向量: [[1]
 [2]
 [3]]


#### 数组的拼接和分裂

In [62]:
# np.concatenate将数组元组或数组列表作为第一个参数
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [63]:
# 一次拼接两个以上数组
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [66]:
# 二维数组的拼接,默认沿axis=0进行拼接
# 第0轴沿着行的垂直往下，第1轴沿着列的方向水平延伸
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [70]:
# 二维数组的拼接,沿axis=1进行拼接
# 第0轴沿着行的垂直往下，第1轴沿着列的方向水平延伸
np.concatenate([grid,grid],axis=1) #参数为列表对象

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [78]:
# 使用np.vstack(垂直栈)和np.hstack(水平栈)实现同样的拼接
ar1 = np.array([1,2,3])
ar2 = np.array([[3,2,1],[4,5,6]])
ar3 = np.array([[99],[99]])
np.vstack((ar1,ar2)) #参数为元组对象

array([[1, 2, 3],
       [3, 2, 1],
       [4, 5, 6]])

In [79]:
np.hstack((ar2,ar3))

array([[ 3,  2,  1, 99],
       [ 4,  5,  6, 99]])

In [83]:
# 数组的分裂
x = [1,3,3,99,99,3,2,1,88]
x1, x2, x3  = np.split(x, [3,5]) #索引列表记录的是分裂点位置,N个分裂点得到N+1个子数组
print(x1,x2,x3)

[1 3 3] [99 99] [ 3  2  1 88]


In [87]:
# np.hsplit与np.vsplit,np.dsplit将数组沿着第三个维度分裂
grid = np.arange(16).reshape((4,4))
upper,lower = np.vsplit(grid, [2]) #按照索引在垂直方向分列
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [88]:
left,right = np.hsplit(grid,[2]) #按照索引在水平方向分裂
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#### Numpy数组的计算：通用函数

In [109]:
# 计算数组每个元素的倒数,列表解析实现方法
np.random.seed(0)
ar = np.random.randint(1,100,size=1000000)
%timeit [1/i for i in ar]

450 ms ± 8.76 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [104]:
# 利用函数实现,循环过程的速度会更慢
ar = np.random.randint(1,10,size = 5)
def compute_reci(a):
    output = np.empty(len(a))
    for i in range(len(a)):
        output[i] = 1/a[i]
    return output
compute_reci(ar)

array([1.        , 0.33333333, 0.25      , 0.11111111, 0.5       ])

In [108]:
# 测试代码运行时间
ar = np.random.randint(1,100,size = 1000000)
%timeit compute_reci(ar)

571 ms ± 8.85 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [110]:
# np.linspace()函数参数 endpoint默认为真，即包含停止值
np.linspace(0,np.pi,3)

array([0.        , 1.57079633, 3.14159265])

In [112]:
L = np.random.random(1000)
%timeit sum(L)

217 µs ± 4.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [113]:
%timeit np.sum(L)

7.07 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
ar.mean(dk)

### Pandas数据处理

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
pd.__version__

'0.23.4'

#### Series对象

In [5]:
data = pd.Series([0.25, 0.5, 0.75, 1])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [8]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [9]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
data[1]

0.5

In [11]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [12]:
data = pd.Series([0.25, 0.5 , 0.75, 1], index = list('abcd'))
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
A = np.array([[3,8,2,4],[2,6,4,8],[6,1,3,8]])
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [15]:
df = pd.DataFrame(A, columns=list('QRST'))
df

Q  R  S  T
0  3  8  2  4
1  2  6  4  8
2  6  1  3  8

In [17]:
df-df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [22]:
df.subtract(df['R'],axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

#### 合并数据集：Concat与Append操作

In [1]:
import numpy as np
import pandas as pd

In [4]:
def make_df(cols, ind):
    data = {c:[str(c)+str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)
df = make_df("ABC",range(3))